-- tables have to be emptied because data.sql from main is always loaded
DELETE FROM CONFIGURATION
DELETE FROM CUBE_FACE
DELETE FROM GAME_USER
DELETE FROM GAME_TEAM
DELETE FROM GROUPING_HELPER
DELETE FROM INTERVAL_TABLE
DELETE FROM ROUND
DELETE FROM TEAM_USER
DELETE FROM TEAM
DELETE FROM TERM
DELETE FROM THRESHOLD_TABLE
DELETE FROM GAME
DELETE FROM TOPIC
DELETE FROM CUBE
DELETE FROM USER_ROLE
DELETE FROM USER
